[workspace]
name = "mdh-knime"
channels = ["knime/label/nightly", "knime", "conda-forge", "graudata"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
packaging = "*"
python = "3.11.*"
knime-extension = ">=5.5.0"
knime-python-base = ">=5.5.0"
markdown = "*"
pandas = "*"
mdh = { version = "3.3.0.*", channel = "graudata" }

[pypi-dependencies]

[feature.build.dependencies]
python = "3.9.*"
knime-extension-bundling = ">=5.5.0"

[feature.build.tasks]
build = { args = [{ "arg" = "dest", "default" = "./local-update-site" }], cmd = "python ./.pixi/envs/build/bin/build_python_extension.py . {{ dest }}"}

[environments]
build = {features = ["build"], no-default-feature = true}